# SwiftLint Configuration for Zest

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - trailing_comma
  # WindowManager requires force casts for macOS Accessibility API (AXUIElement, AXValue)
  # These casts are safe as confirmed by Swift compiler (conditional casts always succeed)
  - force_cast
  # EmojiData.swift contains static emoji data which exceeds normal type body length
  - type_body_length

# Opt-in rules (QA-3 to QA-7)
opt_in_rules:
  # QA-3: Unused Code Detection
  - unused_declaration

  # QA-4: Code Complexity
  - cyclomatic_complexity

  # QA-5: Function Size Warnings
  - function_body_length

  # QA-6: Naming Conventions
  - type_name
  - identifier_name

  # QA-7: Security Issues
  - force_try
  - implicitly_unwrapped_optional

# Rule configurations
cyclomatic_complexity:
  warning: 10
  error: 20

function_body_length:
  warning: 50
  error: 100

# Line length - allow 150 for modern screens
line_length:
  warning: 150
  error: 200

# CommandPaletteWindow.swift is intentionally large - exclude from file_length
file_length:
  warning: 600
  error: 800

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 1
  max_length: 50

# Analyzer rules (run with --analyze)
analyzer_rules:
  # Note: unused_declaration is in opt_in_rules above

included:
  - Sources

excluded:
  - .build
  - Tests
  - tests
  - scripts
  - Sources/UI/CommandPalette/CommandPaletteWindow.swift
  - Sources/Models/Quicklink.swift
  - Sources/Services/AIService.swift
  - Sources/Services/EmojiSearchService.swift
  - Sources/Services/UserCommandsService.swift
