import Foundation

/// Emoji data: emoji character, keywords for search
enum EmojiData {
    static let emojis: [(emoji: String, keywords: [String])] = [
        // Face emojis
        ("😀", ["smile", "happy", "grin", "face"]),
        ("😃", ["happy", "big smile", "face"]),
        ("😄", ["happy", "laugh", "smile"]),
        ("😁", ["grin", "happy", "smile"]),
        ("😆", ["laugh", "lol", "happy"]),
        ("😅", ["laugh", "sweat", "smile"]),
        ("🤣", ["rofl", "laugh", "lol"]),
        ("😂", ["laugh", "cry", "funny"]),
        ("🙂", ["smile", "slight smile"]),
        ("😊", ["happy", "smile", "blush"]),
        ("😇", ["angel", "innocent", "blessed"]),
        ("🥰", ["love", "heart", "crush"]),
        ("😍", ["love", "heart eyes", "crush"]),
        ("🤩", ["star eyes", "excited"]),
        ("😘", ["kiss", "love"]),
        ("😋", ["yum", "tasty", "lick lips"]),
        ("😛", ["tongue", "playful"]),
        ("😜", ["wink", "tongue", "playful"]),
        ("🤪", ["crazy", "zany", "goofy"]),
        ("🤑", ["money", "rich", "dollar"]),
        ("🤗", ["hug", "hugging"]),
        ("🤔", ["think", "hmm", "question"]),
        ("🤐", ["zip", "quiet", "secret"]),
        ("😐", ["neutral", "meh"]),
        ("😑", ["expressionless", "neutral"]),
        ("😶", ["no mouth", "silent"]),
        ("😏", ["smirk", "sly"]),
        ("😒", ["unamused", "annoyed"]),
        ("🙄", ["eye roll", "annoyed"]),
        ("😬", ["awkward", "nervous"]),
        ("🤥", ["lie", "lying"]),
        ("😔", ["sad", "pensive"]),
        ("😪", ["sleepy", "tired"]),
        ("🤤", ["drool", "want"]),
        ("😴", ["sleep", "zzz"]),
        ("🤧", ["sneeze", "achoo"]),
        ("😷", ["mask", "sick"]),
        ("🤒", ["sick", "fever"]),
        ("🤕", ["hurt", "injury"]),
        ("🤢", ["sick", "vomit"]),
        ("🤮", ["vomit", "sick"]),
        ("🤧", ["sneeze"]),
        ("🥵", ["hot", "hot face"]),
        ("🥶", ["cold", "freezing"]),
        ("🥴", ["dizzy", "woozy"]),
        ("😵", ["dizzy", "face"]),
        ("🤯", ["mind blown", "shocked"]),
        ("🤠", ["cowboy", "hat"]),
        ("🥳", ["party", "celebrate"]),
        ("😎", ["cool", "sunglasses"]),
        ("🤓", ["nerd", "glasses"]),
        ("🧐", ["monocle", "fancy"]),

        // Gestures
        ("👋", ["wave", "hello", "bye"]),
        ("🤚", ["hand", "raised"]),
        ("🖐", ["hand", "five"]),
        ("✋", ["high five", "stop"]),
        ("🖖", ["vulcan", "spock"]),
        ("👌", ["ok", "perfect"]),
        ("🤌", ["Italian", "perfect"]),
        ("🤏", ["small", "tiny"]),
        ("✌️", ["victory", "peace"]),
        ("🤞", ["luck", "fingers crossed"]),
        ("🤟", ["love", "rock"]),
        ("🤘", ["rock", "horns"]),
        ("🤙", ["call", "shaka"]),
        ("👈", ["point left"]),
        ("👉", ["point right"]),
        ("👆", ["point up"]),
        ("👇", ["point down"]),
        ("☝️", ["point up", "one"]),
        ("👍", ["thumbs up", "good", "ok"]),
        ("👎", ["thumbs down", "bad"]),
        ("✊", ["fist", "raised"]),
        ("👊", ["fist bump"]),
        ("🤛", ["fist left"]),
        ("🤜", ["fist right"]),
        ("👏", ["clap", "bravo"]),
        ("🙌", ["hooray", "celebrate"]),
        ("👐", ["hands open"]),
        ("🤲", ["palms up", "pray"]),
        ("🤝", ["handshake", "deal"]),
        ("🙏", ["pray", "thanks"]),
        ("✍️", ["write", "type"]),
        ("💅", ["nail", "manicure"]),
        ("🤳", ["selfie"]),
        ("💪", ["muscle", "strong"]),

        // Hearts
        ("❤️", ["heart", "love", "red"]),
        ("🧡", ["heart", "orange", "love"]),
        ("💛", ["heart", "yellow", "love"]),
        ("💚", ["heart", "green", "love"]),
        ("💙", ["heart", "blue", "love"]),
        ("💜", ["heart", "purple", "love"]),
        ("🖤", ["heart", "black", "love"]),
        ("🤍", ["heart", "white"]),
        ("🤎", ["heart", "brown"]),
        ("💔", ["heartbreak", "sad", "broken"]),
        ("❣️", ["heart", "exclamation"]),
        ("💕", ["hearts", "love"]),
        ("💞", ["hearts", "love"]),
        ("💓", ["heartbeat", "love"]),
        ("💗", ["heart", "growing"]),
        ("💖", ["heart", "sparkle"]),
        ("💘", ["heart", "arrow"]),
        ("💝", ["heart", "gift"]),

        // Animals
        ("🐶", ["dog", "puppy"]),
        ("🐱", ["cat", "kitten"]),
        ("🐭", ["mouse"]),
        ("🐹", ["hamster"]),
        ("🐰", ["bunny", "rabbit"]),
        ("🦊", ["fox"]),
        ("🐻", ["bear"]),
        ("🐼", ["panda"]),
        ("🐨", ["koala"]),
        ("🦁", ["lion"]),
        ("🐯", ["tiger"]),
        ("🐮", ["cow"]),
        ("🐷", ["pig"]),
        ("🐸", ["frog"]),
        ("🐵", ["monkey"]),
        ("🐔", ["chicken"]),
        ("🐧", ["penguin"]),
        ("🐦", ["bird"]),
        ("🦆", ["duck"]),
        ("🦅", ["eagle"]),
        ("🦉", ["owl"]),
        ("🦇", ["bat"]),
        ("🐺", ["wolf"]),
        ("🐗", ["boar"]),
        ("🦄", ["unicorn"]),
        ("🐝", ["bee", "honey"]),
        ("🐛", ["caterpillar"]),
        ("🦋", ["butterfly"]),
        ("🐌", ["snail"]),
        ("🐞", ["ladybug"]),
        ("🐜", ["ant"]),
        ("🦟", ["mosquito"]),
        ("🦗", ["cricket"]),

        // Food
        ("🍎", ["apple", "fruit"]),
        ("🍐", ["pear", "fruit"]),
        ("🍊", ["orange", "fruit"]),
        ("🍋", ["lemon", "fruit"]),
        ("🍌", ["banana", "fruit"]),
        ("🍉", ["watermelon", "fruit"]),
        ("🍇", ["grapes", "fruit"]),
        ("🍓", ["strawberry", "fruit"]),
        ("🫐", ["blueberry", "fruit"]),
        ("🍈", ["melon"]),
        ("🍒", ["cherries", "fruit"]),
        ("🍑", ["peach", "fruit"]),
        ("🥭", ["mango"]),
        ("🍍", ["pineapple"]),
        ("🥥", ["coconut"]),
        ("🥝", ["kiwi"]),
        ("🍅", ["tomato"]),
        ("🥑", ["avocado"]),
        ("🍆", ["eggplant"]),
        ("🥔", ["potato"]),
        ("🥕", ["carrot"]),
        ("🌽", ["corn"]),
        ("🌶️", ["pepper"]),
        ("🥒", ["cucumber"]),
        ("🥬", ["lettuce"]),
        ("🥦", ["broccoli"]),
        ("🧄", ["garlic"]),
        ("🧅", ["onion"]),
        ("🍄", ["mushroom"]),
        ("🥜", ["peanut"]),
        ("🌰", ["chestnut"]),
        ("🍞", ["bread"]),
        ("🥐", ["croissant"]),
        ("🥖", ["baguette"]),
        ("🥨", ["pretzel"]),
        ("🥞", ["pancakes"]),
        ("🧇", ["waffle"]),
        ("🧀", ["cheese"]),
        ("🥚", ["egg"]),
        ("🍳", ["cooking", "breakfast"]),
        ("🧈", ["butter"]),
        ("🥓", ["bacon"]),
        ("🥩", ["steak"]),
        ("🍗", ["chicken leg"]),
        ("🍖", ["meat"]),
        ("🦴", ["bone"]),
        ("🌭", ["hot dog"]),
        ("🍔", ["burger"]),
        ("🍟", ["fries"]),
        ("🍕", ["pizza"]),
        ("🥪", ["sandwich"]),
        ("🥙", ["pita"]),
        ("🌮", ["taco"]),
        ("🌯", ["burrito"]),
        ("🥗", ["salad"]),
        ("🥘", ["curry"]),
        ("🍝", ["pasta"]),
        ("🍜", ["ramen"]),
        ("🍲", ["rice bowl"]),
        ("🍛", ["curry"]),
        ("🍣", ["sushi"]),
        ("🍱", ["bento"]),
        ("🥟", ["dumpling"]),
        ("🦪", ["oyster"]),
        ("🍤", ["shrimp"]),
        ("🍙", ["rice ball"]),
        ("🍚", ["rice"]),
        ("🍘", ["rice cracker"]),
        ("🍥", ["fish cake"]),
        ("🥠", ["fortune cookie"]),
        ("🥡", ["takeout"]),
        ("🍢", ["oden"]),
        ("🍡", ["dango"]),
        ("🍧", ["shaved ice"]),
        ("🍨", ["ice cream"]),
        ("🍦", ["ice cream"]),
        ("🥧", ["pie"]),
        ("🧁", ["cupcake"]),
        ("🍰", ["cake"]),
        ("🎂", ["birthday", "cake"]),
        ("🍮", ["pudding"]),
        ("🍭", ["lollipop"]),
        ("🍬", ["candy"]),
        ("🍫", ["chocolate"]),
        ("🍿", ["popcorn"]),
        ("🍩", ["donut"]),
        ("🍪", ["cookie"]),
        ("🌰", ["chestnut"]),
        ("🥜", ["peanut"]),
        ("🍯", ["honey"]),
        ("🥛", ["milk"]),
        ("🍼", ["bottle"]),
        ("☕", ["coffee", "hot"]),
        ("🍵", ["tea"]),
        ("🧃", ["juice"]),
        ("🥤", ["drink"]),
        ("🍶", ["sake"]),
        ("🍺", ["beer"]),
        ("🍻", ["beers"]),
        ("🍷", ["wine"]),
        ("🥂", ["cheers"]),
        ("🍸", ["cocktail"]),
        ("🍹", ["tropical"]),
        ("🧉", ["mate"]),
        ("🍾", ["champagne"]),

        // Flags
        ("🇺🇸", ["flag", "us", "usa", "america", "united states"]),
        ("🇬🇧", ["flag", "uk", "britain", "england"]),
        ("🇨🇦", ["flag", "canada"]),
        ("🇦🇺", ["flag", "australia"]),
        ("🇩🇪", ["flag", "germany"]),
        ("🇫🇷", ["flag", "france"]),
        ("🇮🇹", ["flag", "italy"]),
        ("🇪🇸", ["flag", "spain"]),
        ("🇯🇵", ["flag", "japan"]),
        ("🇰🇷", ["flag", "korea"]),
        ("🇨🇳", ["flag", "china"]),
        ("🇮🇳", ["flag", "india"]),
        ("🇧🇷", ["flag", "brazil"]),
        ("🇲🇽", ["flag", "mexico"]),
        ("🇷🇺", ["flag", "russia"]),
        ("🇳🇱", ["flag", "netherlands"]),
        ("🇸🇪", ["flag", "sweden"]),
        ("🇨🇭", ["flag", "switzerland"]),
        ("🇵🇱", ["flag", "poland"]),
        ("🇹🇷", ["flag", "turkey"]),
        ("🇿🇦", ["flag", "south africa"]),
        ("🇳🇬", ["flag", "nigeria"]),
        ("🇪🇬", ["flag", "egypt"]),
        ("🇮🇪", ["flag", "ireland"]),
        ("🇳🇴", ["flag", "norway"]),
        ("🇩🇰", ["flag", "denmark"]),
        ("🇫🇮", ["flag", "finland"]),
        ("🇦🇹", ["flag", "austria"]),
        ("🇧🇪", ["flag", "belgium"]),
        ("🇵🇹", ["flag", "portugal"]),
        ("🇬🇷", ["flag", "greece"]),
        ("🇮🇱", ["flag", "israel"]),
        ("🇦🇪", ["flag", "uae"]),
        ("🇸🇬", ["flag", "singapore"]),
        ("🇳🇿", ["flag", "new zealand"]),

        // Objects
        ("⌚", ["watch", "time"]),
        ("📱", ["phone", "iphone"]),
        ("💻", ["computer", "laptop"]),
        ("⌨️", ["keyboard"]),
        ("🖥️", ["computer", "desktop"]),
        ("🖨️", ["printer"]),
        ("🖱️", ["mouse"]),
        ("💽", ["disk"]),
        ("💾", ["floppy"]),
        ("💿", ["cd", "disc"]),
        ("📀", ["dvd"]),
        ("📼", ["vhs"]),
        ("📷", ["camera"]),
        ("📸", ["camera", "flash"]),
        ("📹", ["video"]),
        ("🎥", ["movie"]),
        ("📞", ["phone"]),
        ("☎️", ["phone"]),
        ("📟", ["pager"]),
        ("📠", ["fax"]),
        ("📺", ["tv", "television"]),
        ("📻", ["radio"]),
        ("🎙️", ["microphone"]),
        ("🎚️", ["slider"]),
        ("🎛️", ["knobs"]),
        ("🧭", ["compass"]),
        ("⏱️", ["stopwatch"]),
        ("⏲️", ["timer"]),
        ("⏰", ["alarm"]),
        ("🕰️", ["clock"]),
        ("💡", ["light bulb", "idea"]),
        ("🔦", ["flashlight"]),
        ("🕯️", ["candle"]),
        ("🪔", ["lamp"]),
        ("🧯", ["fire extinguisher"]),
        ("🛒", ["cart", "shopping"]),
        ("💰", ["money", "bag"]),
        ("💴", ["yen"]),
        ("💵", ["dollar"]),
        ("💶", ["euro"]),
        ("💷", ["pound"]),
        ("💎", ["gem", "diamond"]),
        ("🔪", ["knife"]),
        ("🗡️", ["sword"]),
        ("⚔️", ["swords"]),
        ("🔨", ["hammer"]),
        ("🪓", ["axe"]),
        ("⛏️", ["pick"]),
        ("🔧", ["wrench"]),
        ("🔩", ["nut", "bolt"]),
        ("⚙️", ["gear"]),
        ("🗜️", ["clamp"]),
        ("⚖️", ["scale"]),
        ("🦯", ["white cane"]),
        ("🔗", ["link"]),
        ("⛓️", ["chain"]),
        ("🧰", ["toolbox"]),
        ("🧲", ["magnet"]),
        ("🪜", ["ladder"]),
        ("🪣", ["bucket"]),
        ("🧪", ["test tube"]),
        ("🧫", ["petri dish"]),
        ("🧬", ["dna"]),
        ("💊", ["pill"]),
        ("💉", ["syringe"]),
        ("🩸", ["blood"]),
        ("🩹", ["bandage"]),
        ("🩺", ["stethoscope"]),
        ("🚑", ["ambulance"]),
        ("🏥", ["hospital"]),
        ("🧼", ["soap"]),
        ("🪥", ["toothbrush"]),
        ("🧽", ["sponge"]),
        ("🪒", ["razor"]),
        ("🧴", ["lotion"]),
        ("🛎️", ["bell"]),
        ("🔑", ["key"]),
        ("🗝️", ["key"]),
        ("🚪", ["door"]),
        ("🪑", ["chair"]),
        ("🛋️", ["couch"]),
        ("🛏️", ["bed"]),
        ("🛌", ["sleeping"]),
        ("🧸", ["teddy", "bear"]),
        ("🪆", ["marionette"]),
        ("🎁", ["gift", "present"]),
        ("🎈", ["balloon"]),
        ("🎏", ["fish"]),
        ("🎀", ["ribbon"]),
        ("🎊", ["confetti"]),
        ("🎉", ["party"]),
        ("🎎", ["dolls"]),
        ("🏮", ["lantern"]),
        ("🪔", ["lamp"]),
        ("🎐", ["wind chime"]),
        ("🧧", ["red envelope"]),
        ("📩", ["email"]),
        ("📧", ["email"]),
        ("📥", ["inbox"]),
        ("📤", ["outbox"]),
        ("📦", ["package", "box"]),
        ("📫", ["mailbox"]),
        ("📪", ["mailbox"]),
        ("📬", ["mailbox"]),
        ("📭", ["mailbox"]),
        ("📮", ["postbox"]),
        ("📯", ["horn"]),
        ("📜", ["scroll"]),
        ("📃", ["document"]),
        ("📄", ["page"]),
        ("📑", ["bookmark"]),
        ("🧷", ["pin"]),
        ("🧸", ["teddy"]),
        ("📎", ["paperclip"]),
        ("📐", ["ruler"]),
        ("📏", ["ruler"]),
        ("🗂️", ["dividers"]),
        ("📅", ["calendar"]),
        ("📆", ["calendar"]),
        ("🗒️", ["notepad"]),
        ("🗓️", ["calendar"]),
        ("📇", ["card index"]),
        ("📈", ["chart", "up"]),
        ("📉", ["chart", "down"]),
        ("📊", ["chart"]),
        ("📋", ["clipboard"]),
        ("📁", ["folder"]),
        ("📂", ["folder"]),
        ("🗂️", ["folder"]),
        ("🗃️", ["folder"]),
        ("🗄️", ["file cabinet"]),
        ("🗑️", ["trash"]),

        // Symbols
        ("❤️", ["heart", "red"]),
        ("🧡", ["orange heart"]),
        ("💛", ["yellow heart"]),
        ("💚", ["green heart"]),
        ("💙", ["blue heart"]),
        ("💜", ["purple heart"]),
        ("🖤", ["black heart"]),
        ("💔", ["broken heart"]),
        ("❣️", ["heart exclamation"]),
        ("💕", ["two hearts"]),
        ("💞", ["revolving hearts"]),
        ("💓", ["beating heart"]),
        ("💗", ["growing heart"]),
        ("💖", ["sparkling heart"]),
        ("💘", ["heart with arrow"]),
        ("💝", ["heart with ribbon"]),
        ("✨", ["sparkles"]),
        ("⭐", ["star"]),
        ("🌟", ["glowing star"]),
        ("💫", ["dizzy star"]),
        ("🌠", ["shooting star"]),
        ("🌌", ["milky way"]),
        ("☀️", ["sun"]),
        ("🌤️", ["sun small"]),
        ("⛅", ["sun behind cloud"]),
        ("🌥️", ["sun large cloud"]),
        ("☁️", ["cloud"]),
        ("🌦️", ["sun rain"]),
        ("🌧️", ["rain"]),
        ("⛈️", ["thunder"]),
        ("🌩️", ["lightning"]),
        ("🌨️", ["snow"]),
        ("❄️", ["snowflake"]),
        ("☃️", ["snowman"]),
        ("⛄", ["snowman"]),
        ("🌪️", ["tornado"]),
        ("🌈", ["rainbow"]),
        ("🌂", ["umbrella"]),
        ("💧", ["droplet"]),
        ("💦", ["sweat drops"]),
        ("☔", ["umbrella"]),
        ("⚡", ["lightning", "zap"]),
        ("🔥", ["fire", "hot"]),
        ("💥", ["collision", "boom"]),
        ("💢", ["anger"]),
        ("💬", ["speech"]),
        ("👁️‍🗨️", ["eye speech"]),
        ("🗯️", ["anger speech"]),
        ("💭", ["thought"]),
        ("💤", ["zzz", "sleep"]),
        ("♠️", ["spade"]),
        ("♣️", ["club"]),
        ("♥️", ["heart"]),
        ("♦️", ["diamond"]),
        ("🃏", ["cards"]),
        ("🎴", ["flower"]),
        ("🀄", ["mahjong"]),
        ("🎰", ["slot machine"]),
        ("🎱", ["8 ball"]),
        ("🎳", ["bowling"]),
        ("⚽", ["soccer"]),
        ("🏀", ["basketball"]),
        ("🏈", ["football"]),
        ("⚾", ["baseball"]),
        ("🥎", ["softball"]),
        ("🎾", ["tennis"]),
        ("🏐", ["volleyball"]),
        ("🏉", ["rugby"]),
        ("🥏", ["frisbee"]),
        ("🎱", ["ball"]),
        ("🪀", ["yo-yo"]),
        ("🏓", ["ping pong"]),
        ("🏸", ["badminton"]),
        ("🏒", ["hockey"]),
        ("🏑", ["lacrosse"]),
        ("🥍", ["lacrosse"]),
        ("🏏", ["cricket"]),
        ("🪃", ["boomerang"]),
        ("🥅", ["goal"]),
        ("⛳", ["golf"]),
        ("🪁", ["kite"]),
        ("🏹", ["archery"]),
        ("🎣", ["fishing"]),
        ("🤿", ["diving"]),
        ("🥊", ["boxing glove"]),
        ("🥋", ["karate"]),
        ("🎽", ["jersey"]),
        ("🛹", ["skateboard"]),
        ("🛼", ["roller skate"]),
        ("🛷", ["sleigh"]),
        ("⛸️", ["skate"]),
        ("🥌", ["curling stone"]),
        ("🎿", ["ski"]),
        ("⛷️", ["skier"]),
        ("🏂", ["snowboard"]),
        ("🪂", ["parachute"]),
        ("🏋️", ["weightlift"]),
        ("🤼", ["wrestling"]),
        ("🤸", ["gymnastics"]),
        ("⛹️", ["basketball player"]),
        ("🤺", ["fencing"]),
        ("🤾", ["handball"]),
        ("🏌️", ["golf"]),
        ("🏇", ["horse racing"]),
        ("🧘", ["yoga"]),
        ("🏄", ["surf"]),
        ("🏊", ["swim"]),
        ("🤽", ["water polo"]),
        ("🚣", ["rowboat"]),
        ("🧗", ["climbing"]),
        ("🚵", ["mountain bike"]),
        ("🚴", ["bike"]),
        ("🏆", ["trophy"]),
        ("🥇", ["gold medal"]),
        ("🥈", ["silver medal"]),
        ("🥉", ["bronze medal"]),
        ("🏅", ["medal"]),
        ("🎖️", ["medal"]),
        ("🏵️", ["rosette"]),
        ("🎗️", ["ribbon"]),
        ("🎫", ["ticket"]),
        ("🎟️", ["ticket"]),
        ("🎪", ["circus"]),
        ("🤹", ["juggler"]),
        ("🎭", ["theater"]),
        ("🖼️", ["frame"]),
        ("🎨", ["art"]),
        ("🧵", ["thread"]),
        ("🪡", ["needle"]),
        ("🧶", ["yarn"]),
        ("🪢", ["knot"]),
        ("👗", ["dress"]),
        ("👘", ["kimono"]),
        ("🥻", ["sari"]),
        ("🩱", ["bikini"]),
        ("👙", ["bikini"]),
        ("👚", ["shirt"]),
        ("👕", ["t-shirt"]),
        ("👖", ["jeans"]),
        ("🧣", ["scarf"]),
        ("🧤", ["gloves"]),
        ("🧥", ["coat"]),
        ("🧦", ["socks"]),
        ("👗", ["dress"]),
        ("👠", ["heels"]),
        ("👡", ["sandal"]),
        ("👢", ["boot"]),
        ("👟", ["sneaker"]),
        ("🥾", ["boot"]),
        ("🥿", ["flat shoe"]),
        ("👒", ["hat"]),
    ]
}
